# Generated by Django 4.2.6 on 2023-10-13 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('yaratilma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('yas', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mission_owner', models.CharField(max_length=255)),
                ('mission_desc', models.TextField(blank=True, null=True)),
                ('yaratilma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='missions.user')),
            ],
        ),
    ]
