# Generated by Django 4.2.6 on 2023-10-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mission_Finished',
            field=models.BooleanField(default=False),
        ),
    ]
