# Generated by Django 4.2.6 on 2023-10-13 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_mission_mission_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='guncellenme_tarihi',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='mission_owner',
        ),
    ]
